site_name: OpenObserve Documentation

# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin required for nav
plugins:
  - search
  - awesome-pages
  - material-plausible
# nav:
#   - index.md
#   - getting-started.md
#   - installation.md
#   - ...
#   - monitoring.md
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/openapi-explorer@0/dist/browser/openapi-explorer.min.js
  - js/ms-clarity.js
  - js/zinc.js
  - js/vector_co.js
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/zinclabsinc
    - icon: fontawesome/brands/github 
      link: https://github.com/openobserve/openobserve
    - icon: fontawesome/brands/docker 
      link: https://gallery.ecr.aws/zinclabs/openobserve
    - icon: fontawesome/brands/slack 
      link: https://join.slack.com/t/zincobserve/shared_invite/zt-11r96hv2b-UwxUILuSJ1duzl_6mhJwVg
  alternate:
    # - name: English
    #   link: /en/ 
    #   lang: en
    # - name: Chinese
    #   link: /cn/
    #   lang: zh
  generator: false
  version:
    provider: mike
  analytics:
    provider: google
    property: G-3383ZJ2HH7
    domain: openobserve.ai
    # feedback:
    #   title: Was this page helpful?
    #   ratings:
    #     - icon: material/emoticon-happy-outline
    #       name: This page was helpful
    #       data: good
    #       note: >-
    #         Thanks for your feedback!

    #     - icon: material/emoticon-sad-outline
    #       name: This page could be improved
    #       data: bad
    #       note: >-
    #         Thanks for your feedback! Help us improve this page by
    #         using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
theme:
  logo: images/logo_circle.png
  favicon: images/logo_circle.png
  name: material
  custom_dir: overrides
  features:
    # - navigation.expand
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.code.select
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
repo_url: https://github.com/openobserve/openobserve
repo_name: openobserve/openobserve
edit_uri: https://github.com/openobserve/openobserve-docs/edit/main/docs/
markdown_extensions:
  - tables
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
